title: Sweet Potato Press               
email: 7yr@protonmail.com

markdown: kramdown
highlighter: rouge

baseurl: /
permalink: /:title

releases: 'releases.html'
about: 'about.html'
social: 'social.html'
